apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-082d5aad9daa79463
    fsType: ext4